# Generated by Django 2.0.4 on 2018-04-24 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='agama',
            field=models.CharField(choices=[('islam', 'ISLAM'), ('kristen', 'KRISTER'), ('budha', 'BUDHA')], default='green', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='alamat',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
