# Generated by Django 2.0.4 on 2018-04-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20180424_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='agama',
            field=models.CharField(choices=[('islam', 'ISLAM'), ('kristen', 'KRISTER'), ('budha', 'BUDHA')], default='null', max_length=20),
        ),
    ]
